[versions]
agp = "8.3.0"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
composeBom = "2023.08.00"
dagger-hilt ="2.51"
retrofit = "2.9.0"
okhttp = "4.9.1"
gson = "2.8.6"
firebaseCrashlyticsBuildtools = "2.9.9"
hilt-compose = "1.2.0"
coil = "2.6.0"
compose-navigation = "2.7.7"
compose-constraint = "1.0.1"
room-version = "2.6.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
dagger-hilt-android = {module ="com.google.dagger:hilt-android", version.ref = "dagger-hilt"}
dagger-hilt-compiler = {module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger-hilt"}
retrofit  = {module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
retrofit-gson  = {module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
retrofit-converter-gson  = {module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit"}
retrofit-okhttp  = {module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
retrofit-urlConnection  = {module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp"}
retrofit-logging  = {module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp"}
gson  = {module = "com.google.code.gson:gson", version.ref = "gson"}
dagger-hilt-compose  = {module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-compose"}
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
coil = {module = "io.coil-kt:coil-compose" , version.ref = "coil"}
compose-navigation = {module = "androidx.navigation:navigation-compose" , version.ref = "compose-navigation"}
compose-constraint = {module = "androidx.constraintlayout:constraintlayout-compose" , version.ref = "compose-constraint"}
room-runtime = {module = "androidx.room:room-runtime", version.ref = "room-version"}
room-compiler = {module = "androidx.room:room-compiler", version.ref = "room-version"}
room-kapt = {module = "androidx.room:room-compiler", version.ref = "room-version"}
room-ktx = {module = "androidx.room:room-ktx", version.ref = "room-version"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }

